name: Lint_Test
3on: push
4
5jobs:
6  test:
7    runs-on: ubuntu-latest
8    timeout-minutes: 10
9
10    steps:
11      - name: Check out repository code
12        uses: actions/checkout@v2
13
15      - name: Setup Python
16        uses: actions/setup-python@v2
17        with:
18          python-version: "3.8"

        - name: Install Dependencies
          run: |
            python -m pip install --upgrade pipenv wheel
            python -m pip install -r requirements-dev.txt

        - name: Lint
          run: |
            python -m black --check .

        - name: Pytest
          run: |
            python -m pytest --cov-report term-missing --cov=airflow_provider_bigquery_reservation tests

        - name: Upload coverage reports to Codecov
          uses: codecov/codecov-action@v3